{% set name = "silicon" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Aloxaf/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 56e7f3be4118320b64e37a174cc2294484e27b019c59908c0a96680a5ae3ad58

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - pkg-config
    - fontconfig-devel
  host:
    - harfbuzz
    - fontconfig
    - freetype
    - libxcb

test:
  commands:
    - silicon --help

about:
  home: https://github.com/Aloxaf/silicon
  summary: Create beautiful image of your source code.
  dev_url: https://github.com/Aloxaf/silicon
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
